/*
 * The MIT License
 *
 * Copyright 2011 Edwin Bratini <edwin.bratini@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 * EliminacionRegistroDialog.java
 *
 * Created on Nov 9, 2011, 12:45:12 PM
 */
package org.salvador_dali.psychsys.ui;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Edwin Bratini <edwin.bratini@gmail.com>
 */
public class EliminacionRegistroDialog extends javax.swing.JDialog {

    /** Creates new form EliminacionRegistroDialog */
    public EliminacionRegistroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensajeEliminacion = new javax.swing.JLabel();
        chkCambiarStatus = new javax.swing.JCheckBox();
        lblPsychSysLogo = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        spnEntidadEliminar = new javax.swing.JScrollPane();
        txaEntidadEliminar = new javax.swing.JTextArea();
        lblProgressBar = new javax.swing.JLabel();
        btnNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Registro [Estudiantes]");
        setModal(true);
        setResizable(false);

        lblMensajeEliminacion.setText("¿Seguro que desea eliminar este registro?");

        chkCambiarStatus.setSelected(true);
        chkCambiarStatus.setText("Solo cambiar status");

        lblPsychSysLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/borrar estudiantes 65x65.png"))); // NOI18N

        btnSi.setText("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        txaEntidadEliminar.setBackground(java.awt.SystemColor.control);
        txaEntidadEliminar.setColumns(20);
        txaEntidadEliminar.setEditable(false);
        txaEntidadEliminar.setRows(3);
        txaEntidadEliminar.setText("Id: 2010-10\nNombre: Bratini G., Edwin A.\nCurso: 4to de Media");
        txaEntidadEliminar.setWrapStyleWord(true);
        txaEntidadEliminar.setAutoscrolls(false);
        spnEntidadEliminar.setViewportView(txaEntidadEliminar);

        lblProgressBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/circle progress bar 20x20.png"))); // NOI18N

        btnNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPsychSysLogo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnEntidadEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(lblMensajeEliminacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(chkCambiarStatus)
                        .addGap(18, 18, 18)
                        .addComponent(lblProgressBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPsychSysLogo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensajeEliminacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnEntidadEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chkCambiarStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                            .addComponent(lblProgressBar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminacionRegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminacionRegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminacionRegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminacionRegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EliminacionRegistroDialog dialog = new EliminacionRegistroDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnNo() {
        return btnNo;
    }

    public void setBtnNo(JButton btnNo) {
        this.btnNo = btnNo;
    }

    public JButton getBtnSi() {
        return btnSi;
    }

    public void setBtnSi(JButton btnSi) {
        this.btnSi = btnSi;
    }

    public JCheckBox getChkCambiarStatus() {
        return chkCambiarStatus;
    }

    public void setChkCambiarStatus(JCheckBox chkCambiarStatus) {
        this.chkCambiarStatus = chkCambiarStatus;
    }

    public JLabel getLblMensajeEliminacion() {
        return lblMensajeEliminacion;
    }

    public void setLblMensajeEliminacion(JLabel lblMensajeEliminacion) {
        this.lblMensajeEliminacion = lblMensajeEliminacion;
    }

    public JLabel getLblProgressBar() {
        return lblProgressBar;
    }

    public void setLblProgressBar(JLabel lblProgressBar) {
        this.lblProgressBar = lblProgressBar;
    }

    public JLabel getLblPsychSysLogo() {
        return lblPsychSysLogo;
    }

    public void setLblPsychSysLogo(JLabel lblPsychSysLogo) {
        this.lblPsychSysLogo = lblPsychSysLogo;
    }

    public JScrollPane getSpnEntidadEliminar() {
        return spnEntidadEliminar;
    }

    public void setSpnEntidadEliminar(JScrollPane spnEntidadEliminar) {
        this.spnEntidadEliminar = spnEntidadEliminar;
    }

    public JTextArea getTxaEntidadEliminar() {
        return txaEntidadEliminar;
    }

    public void setTxaEntidadEliminar(JTextArea txaEntidadEliminar) {
        this.txaEntidadEliminar = txaEntidadEliminar;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JCheckBox chkCambiarStatus;
    private javax.swing.JLabel lblMensajeEliminacion;
    private javax.swing.JLabel lblProgressBar;
    private javax.swing.JLabel lblPsychSysLogo;
    private javax.swing.JScrollPane spnEntidadEliminar;
    private javax.swing.JTextArea txaEntidadEliminar;
    // End of variables declaration//GEN-END:variables
}
