/*
 * The MIT License
 *
 * Copyright 2011 Edwin Bratini <edwin.bratini@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 * RegistroEdicionAntPsicosocialSexual.java
 *
 * Created on Nov 15, 2011, 5:10:18 PM
 */
package org.salvador_dali.psychsys.ui;

import javax.swing.JOptionPane;
import org.salvador_dali.psychsys.model.entities.AntPsicosocialSexual;

/**
 *
 * @author Edwin Bratini <edwin.bratini@gmail.com>
 */
public class RegistroEdicionAntPsicosocialSexual extends javax.swing.JDialog {

    private RegistroEdicionModo modo = RegistroEdicionModo.REGISTRO;
    private AntPsicosocialSexual aps;
    private AntPsicosocialSexual apsEditar;

    /** Creates new form RegistroEdicionAntPsicosocialSexual */
    public RegistroEdicionAntPsicosocialSexual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AntPsicosocialSexual getAps() {
        return aps;
    }

    public void setAps(AntPsicosocialSexual aps) {
        this.aps = aps;
    }

    public AntPsicosocialSexual getApsEditar() {
        return apsEditar;
    }

    public void setApsEditar(AntPsicosocialSexual apsEditar) {
        this.apsEditar = apsEditar;
    }

    public RegistroEdicionModo getModo() {
        return modo;
    }

    public void setModo(RegistroEdicionModo modo) {
        this.modo = modo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEsfinterAnal = new javax.swing.JLabel();
        spnEsfinterAnal = new javax.swing.JSpinner();
        lblEsfinterVesical = new javax.swing.JLabel();
        spnEsfinterVesical = new javax.swing.JSpinner();
        lblMenarquia = new javax.swing.JLabel();
        spnMenarquia = new javax.swing.JSpinner();
        lblEyaculacion = new javax.swing.JLabel();
        spnEyaculacion = new javax.swing.JSpinner();
        lblCuriosidadSexualActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCuriosidadSexualActual = new javax.swing.JTextArea();
        lblSuenio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaSuenio = new javax.swing.JTextArea();
        lblHabitosAlimenticios = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaHabitosAlimenticios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Antecedentes Psicosocial-Sexual");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        statusMessageLabel.setForeground(new java.awt.Color(0, 153, 51));
        statusMessageLabel.setText("Antecedentes psicosocial-sexual registrado exitosamente.");

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/circle progress bar 20x20.png"))); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel))
                .addContainerGap())
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEsfinterAnal.setText("Esfinter Anal");

        spnEsfinterAnal.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        spnEsfinterAnal.setToolTipText("Edad que el niño(a) dejo de hacerse pupu");

        lblEsfinterVesical.setText("Esfinter Vesical");

        spnEsfinterVesical.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        spnEsfinterVesical.setToolTipText("Edad que el niño(a) dejo de hacerse pipi");

        lblMenarquia.setText("Menarquia");

        spnMenarquia.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        spnMenarquia.setToolTipText("Edad que el niño(a) dejo de hacerse pipi");

        lblEyaculacion.setText("Eyaculacion");

        spnEyaculacion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        spnEyaculacion.setToolTipText("Edad que el niño(a) dejo de hacerse pipi");

        lblCuriosidadSexualActual.setText("Curiosidad Sexual Actual");

        txaCuriosidadSexualActual.setColumns(20);
        txaCuriosidadSexualActual.setLineWrap(true);
        txaCuriosidadSexualActual.setRows(5);
        txaCuriosidadSexualActual.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaCuriosidadSexualActual);

        lblSuenio.setText("Sueño");

        txaSuenio.setColumns(20);
        txaSuenio.setLineWrap(true);
        txaSuenio.setRows(5);
        txaSuenio.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaSuenio);

        lblHabitosAlimenticios.setText("Habitos Alimenticios");

        txaHabitosAlimenticios.setColumns(20);
        txaHabitosAlimenticios.setLineWrap(true);
        txaHabitosAlimenticios.setRows(5);
        txaHabitosAlimenticios.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txaHabitosAlimenticios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEsfinterAnal)
                            .addComponent(lblEsfinterVesical))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnEsfinterAnal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnEsfinterVesical, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEyaculacion)
                            .addComponent(lblMenarquia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnEyaculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnMenarquia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCuriosidadSexualActual)
                            .addComponent(lblSuenio)
                            .addComponent(lblHabitosAlimenticios)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEsfinterAnal)
                    .addComponent(spnEsfinterAnal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenarquia)
                    .addComponent(spnMenarquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEsfinterVesical)
                    .addComponent(spnEsfinterVesical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEyaculacion)
                    .addComponent(spnEyaculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblHabitosAlimenticios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCuriosidadSexualActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSuenio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        statusMessageLabel.setVisible(false);
        statusAnimationLabel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        ProgressCircle pc = new ProgressCircle(statusAnimationLabel);
        pc.start();
        String trabajoCompletoMensaje = "Antecedentes psicosocial sexual registrado exitosamente.";

        // si todo esta bien
        statusMessageLabel.setVisible(false);

        if (modo != null && modo.equals(RegistroEdicionModo.REGISTRO)) {
            aps = new AntPsicosocialSexual();
            aps.setApsEsfinterAnal(Integer.parseInt(spnEsfinterAnal.getValue().toString()));
            aps.setApsEsfinterVecical(Integer.parseInt(spnEsfinterVesical.getValue().toString()));
            aps.setApsMenarquia(Integer.parseInt(spnMenarquia.getValue().toString()));
            aps.setApsEyaculacion(Integer.parseInt(spnEyaculacion.getValue().toString()));
            aps.setApsHabitosAlimenticios(!txaHabitosAlimenticios.getText().isEmpty() ? txaHabitosAlimenticios.getText() : null);
            aps.setApsCuriosidadSexualActual(!txaCuriosidadSexualActual.getText().isEmpty() ? txaCuriosidadSexualActual.getText() : null);
            aps.setApsSuenio(!txaSuenio.getText().isEmpty() ? txaSuenio.getText() : null);

            // se registra cuando le dan aceptar en ventana de historia clinica
        } else if (modo != null && modo.equals(RegistroEdicionModo.EDICION)) {
            apsEditar.setApsEsfinterAnal(Integer.parseInt(spnEsfinterAnal.getValue().toString()));
            apsEditar.setApsEsfinterVecical(Integer.parseInt(spnEsfinterVesical.getValue().toString()));
            apsEditar.setApsMenarquia(Integer.parseInt(spnMenarquia.getValue().toString()));
            apsEditar.setApsEyaculacion(Integer.parseInt(spnEyaculacion.getValue().toString()));
            apsEditar.setApsHabitosAlimenticios(!txaHabitosAlimenticios.getText().isEmpty() ? txaHabitosAlimenticios.getText() : null);
            apsEditar.setApsCuriosidadSexualActual(!txaCuriosidadSexualActual.getText().isEmpty() ? txaCuriosidadSexualActual.getText() : null);
            apsEditar.setApsSuenio(!txaSuenio.getText().isEmpty() ? txaSuenio.getText() : null);

            // se actualiza cuando le dan aceptar en ventana de historia clinica
        }

        pc.stop();
        JOptionPane.showMessageDialog(this, trabajoCompletoMensaje, "Antecedentes Psicosocial Sexual", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionAntPsicosocialSexual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionAntPsicosocialSexual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionAntPsicosocialSexual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionAntPsicosocialSexual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RegistroEdicionAntPsicosocialSexual dialog = new RegistroEdicionAntPsicosocialSexual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCuriosidadSexualActual;
    private javax.swing.JLabel lblEsfinterAnal;
    private javax.swing.JLabel lblEsfinterVesical;
    private javax.swing.JLabel lblEyaculacion;
    private javax.swing.JLabel lblHabitosAlimenticios;
    private javax.swing.JLabel lblMenarquia;
    private javax.swing.JLabel lblSuenio;
    private javax.swing.JSpinner spnEsfinterAnal;
    private javax.swing.JSpinner spnEsfinterVesical;
    private javax.swing.JSpinner spnEyaculacion;
    private javax.swing.JSpinner spnMenarquia;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextArea txaCuriosidadSexualActual;
    private javax.swing.JTextArea txaHabitosAlimenticios;
    private javax.swing.JTextArea txaSuenio;
    // End of variables declaration//GEN-END:variables
}
