/*
 * The MIT License
 *
 * Copyright 2011 Edwin Bratini <edwin.bratini@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 * RegistroEdicionEscolaridad.java
 *
 * Created on Nov 15, 2011, 5:10:33 PM
 */
package org.salvador_dali.psychsys.ui;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import org.salvador_dali.psychsys.model.entities.Escolaridad;

/**
 *
 * @author Edwin Bratini <edwin.bratini@gmail.com>
 */
public class RegistroEdicionEscolaridad extends javax.swing.JDialog {

    private RegistroEdicionModo modo = RegistroEdicionModo.REGISTRO;
    private Escolaridad esc;
    private Escolaridad escEditar;

    /** Creates new form RegistroEdicionEscolaridad */
    public RegistroEdicionEscolaridad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Escolaridad getEsc() {
        return esc;
    }

    public void setEsc(Escolaridad esc) {
        this.esc = esc;
    }

    public Escolaridad getEscEditar() {
        return escEditar;
    }

    public void setEscEditar(Escolaridad escEditar) {
        this.escEditar = escEditar;
    }

    public RegistroEdicionModo getModo() {
        return modo;
    }

    public void setModo(RegistroEdicionModo modo) {
        this.modo = modo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrRecuperacion = new javax.swing.ButtonGroup();
        bgrReprobado = new javax.swing.ButtonGroup();
        bgrCambioEscuela = new javax.swing.ButtonGroup();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEdadInicioEscolaridad = new javax.swing.JLabel();
        spnEdadInicioEscolaridad = new javax.swing.JSpinner();
        cmbNivelEscolar = new javax.swing.JComboBox();
        cmbGradoEscolar = new javax.swing.JComboBox();
        lblCursoActual = new javax.swing.JLabel();
        lblTipoEscuelaActual = new javax.swing.JLabel();
        cmbTipoEscuelaActual = new javax.swing.JComboBox();
        lblRecuperacion = new javax.swing.JLabel();
        rbnRecSi = new javax.swing.JRadioButton();
        rbnRecNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbnRepSi = new javax.swing.JRadioButton();
        rbnRepNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbnCambioEscuelaSi = new javax.swing.JRadioButton();
        rbnCambioEscuelaNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRazonCambioEscuela = new javax.swing.JTextArea();
        lblRendimientoActual = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRendimientoActual = new javax.swing.JTextArea();
        lblVecesReprobacion = new javax.swing.JLabel();
        spnVecesReprobacion = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Informacion de Escolaridad");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        statusMessageLabel.setForeground(new java.awt.Color(0, 153, 51));
        statusMessageLabel.setText("Informacion de escolaridad registrada exitosamente.");

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/circle progress bar 20x20.png"))); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel))
                .addContainerGap())
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEdadInicioEscolaridad.setText("Edad Inicio Escolaridad");

        spnEdadInicioEscolaridad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        cmbNivelEscolar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basica", "Inicial", "Media" }));

        cmbGradoEscolar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbGradoEscolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGradoEscolarActionPerformed(evt);
            }
        });

        lblCursoActual.setText("Curso Actual");

        lblTipoEscuelaActual.setText("Tipo Escuela Actual");

        cmbTipoEscuelaActual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Especial", "Privada", "Publica" }));

        lblRecuperacion.setText("Recuperacion");

        bgrRecuperacion.add(rbnRecSi);
        rbnRecSi.setText("Si");
        rbnRecSi.setToolTipText("Si el niño(a) ha estado en recuperacion");

        bgrRecuperacion.add(rbnRecNo);
        rbnRecNo.setSelected(true);
        rbnRecNo.setText("No");
        rbnRecNo.setToolTipText("Si el niño(a) ha estado en recuperacion");

        jLabel4.setText("Ha Reprobado");

        bgrReprobado.add(rbnRepSi);
        rbnRepSi.setText("Si");

        bgrReprobado.add(rbnRepNo);
        rbnRepNo.setSelected(true);
        rbnRepNo.setText("No");

        jLabel5.setText("Ha Cambiado de Escuela");

        bgrCambioEscuela.add(rbnCambioEscuelaSi);
        rbnCambioEscuelaSi.setText("Si");

        bgrCambioEscuela.add(rbnCambioEscuelaNo);
        rbnCambioEscuelaNo.setSelected(true);
        rbnCambioEscuelaNo.setText("No");

        txaRazonCambioEscuela.setColumns(20);
        txaRazonCambioEscuela.setForeground(new java.awt.Color(204, 204, 204));
        txaRazonCambioEscuela.setLineWrap(true);
        txaRazonCambioEscuela.setRows(3);
        txaRazonCambioEscuela.setText("Escriba por que?");
        txaRazonCambioEscuela.setWrapStyleWord(true);
        txaRazonCambioEscuela.setEnabled(false);
        jScrollPane1.setViewportView(txaRazonCambioEscuela);

        lblRendimientoActual.setText("Rendimiento Actual");

        txaRendimientoActual.setColumns(20);
        txaRendimientoActual.setLineWrap(true);
        txaRendimientoActual.setRows(5);
        txaRendimientoActual.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaRendimientoActual);

        lblVecesReprobacion.setText("Veces");

        spnVecesReprobacion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(lblRecuperacion)
                            .addComponent(lblTipoEscuelaActual)
                            .addComponent(lblCursoActual)
                            .addComponent(lblEdadInicioEscolaridad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbnCambioEscuelaSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbnCambioEscuelaNo))
                            .addComponent(spnEdadInicioEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbGradoEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbNivelEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbTipoEscuelaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbnRecSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbnRecNo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbnRepSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbnRepNo)
                                .addGap(18, 18, 18)
                                .addComponent(lblVecesReprobacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnVecesReprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))
                    .addComponent(lblRendimientoActual)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadInicioEscolaridad)
                    .addComponent(spnEdadInicioEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCursoActual)
                    .addComponent(cmbGradoEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNivelEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEscuelaActual)
                    .addComponent(cmbTipoEscuelaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecuperacion)
                    .addComponent(rbnRecSi)
                    .addComponent(rbnRecNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbnRepSi)
                    .addComponent(rbnRepNo)
                    .addComponent(lblVecesReprobacion)
                    .addComponent(spnVecesReprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbnCambioEscuelaSi)
                    .addComponent(rbnCambioEscuelaNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRendimientoActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        ProgressCircle pc = new ProgressCircle(statusAnimationLabel);
        pc.start();
        String trabajoCompletoMensaje = "Antecedentes psicomotriz lenguaje registrado exitosamente.";

        // si todo esta bien
        statusMessageLabel.setVisible(false);

        if (modo != null && modo.equals(RegistroEdicionModo.REGISTRO)) {
            esc = new Escolaridad(null, Integer.parseInt(spnEdadInicioEscolaridad.getValue().toString()), cmbNivelEscolar.getSelectedItem().toString(),
                    Integer.parseInt(cmbGradoEscolar.getSelectedItem().toString()), cmbTipoEscuelaActual.getSelectedItem().toString(), rbnRecSi.isSelected() ? 'S' : 'N',
                    rbnRepSi.isSelected() ? 'S' : 'N', Integer.parseInt(spnVecesReprobacion.getValue().toString()), rbnCambioEscuelaSi.isSelected() ? 'S' : 'N');
            esc.setEscRazonCambioEscuela(!txaRazonCambioEscuela.getText().isEmpty() ? txaRazonCambioEscuela.getText() : null);
            esc.setEscRendimientoActual(!txaRendimientoActual.getText().isEmpty() ? txaRendimientoActual.getText() : null);

            // se registra cuando le dan aceptar en ventana de historia clinica
        } else if (modo != null && modo.equals(RegistroEdicionModo.EDICION)) {
            escEditar.setEscEdadInicioEscolaridad(Integer.parseInt(spnEdadInicioEscolaridad.getValue().toString()));
            escEditar.setEscNivelEscolar(cmbNivelEscolar.getSelectedItem().toString());
            escEditar.setEscGradoEscolarActual(Integer.parseInt(cmbGradoEscolar.getSelectedItem().toString()));
            escEditar.setEscTipoEscuelaActual(cmbTipoEscuelaActual.getSelectedItem().toString());
            escEditar.setEscRecuperacion(rbnRecSi.isSelected() ? 'S' : 'N');
            escEditar.setEscHaReprobado(rbnRepSi.isSelected() ? 'S' : 'N');
            escEditar.setEscCantVecesReprobacion(Integer.parseInt(spnVecesReprobacion.getValue().toString()));
            escEditar.setEscCambioEscuela(rbnCambioEscuelaSi.isSelected() ? 'S' : 'N');
            escEditar.setEscRazonCambioEscuela(!txaRazonCambioEscuela.getText().isEmpty() ? txaRazonCambioEscuela.getText() : null);
            escEditar.setEscRendimientoActual(!txaRendimientoActual.getText().isEmpty() ? txaRendimientoActual.getText() : null);

            // se actualiza cuando le dan aceptar en ventana de historia clinica
        }

        statusMessageLabel.setText(trabajoCompletoMensaje);
        statusMessageLabel.setForeground(Color.GREEN);
        statusMessageLabel.setVisible(true);
        new Thread(new LabelToolTipShower(statusMessageLabel, 3500)).start();
        pc.stop();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        statusMessageLabel.setVisible(false);
        statusAnimationLabel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void cmbGradoEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradoEscolarActionPerformed
        // TODO add your handling code here:
        int gradoEscolar = Integer.parseInt(cmbGradoEscolar.getSelectedItem().toString());
        if (gradoEscolar >= 5) {
            cmbNivelEscolar.setModel(new DefaultComboBoxModel(new String[]{"Basica"}));
        } else if (gradoEscolar >= 2) {
            cmbNivelEscolar.setModel(new DefaultComboBoxModel(new String[]{"Basica", "Media"}));
        } else if (gradoEscolar >= 1) {
            cmbNivelEscolar.setModel(new DefaultComboBoxModel(new String[]{"Basica", "Inicial", "Media"}));
        }
    }//GEN-LAST:event_cmbGradoEscolarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEdicionEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RegistroEdicionEscolaridad dialog = new RegistroEdicionEscolaridad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrCambioEscuela;
    private javax.swing.ButtonGroup bgrRecuperacion;
    private javax.swing.ButtonGroup bgrReprobado;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbGradoEscolar;
    private javax.swing.JComboBox cmbNivelEscolar;
    private javax.swing.JComboBox cmbTipoEscuelaActual;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCursoActual;
    private javax.swing.JLabel lblEdadInicioEscolaridad;
    private javax.swing.JLabel lblRecuperacion;
    private javax.swing.JLabel lblRendimientoActual;
    private javax.swing.JLabel lblTipoEscuelaActual;
    private javax.swing.JLabel lblVecesReprobacion;
    private javax.swing.JRadioButton rbnCambioEscuelaNo;
    private javax.swing.JRadioButton rbnCambioEscuelaSi;
    private javax.swing.JRadioButton rbnRecNo;
    private javax.swing.JRadioButton rbnRecSi;
    private javax.swing.JRadioButton rbnRepNo;
    private javax.swing.JRadioButton rbnRepSi;
    private javax.swing.JSpinner spnEdadInicioEscolaridad;
    private javax.swing.JSpinner spnVecesReprobacion;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextArea txaRazonCambioEscuela;
    private javax.swing.JTextArea txaRendimientoActual;
    // End of variables declaration//GEN-END:variables
}
